### ISSUE TITLE
Option to disable all keybindings

### ISSUE THREAD

**Issue by SirVer** [1995eaton/chromium-vim#206]
cVim eats too many of the shortcuts I use. For example the exclamation mark switches tabs on my keymap and even disabling cvim or switching to insert mode does not change that. 

Please add an option to disable everything in cvim, all bindings so that I can selectively `:map` what is useful to me.

**Comment by 1995eaton** [comment]
https://github.com/1995eaton/chromium-vim#mappings

**Comment by SirVer** [comment]
Missed that. Thanks and sorry for the noise.

**Comment by SirVer** [comment]
Did not solve my original problem though `!` still switches tabs if I have cvim enabled in my extensions. If it helps, on my keymap `<alt-k>` creates the `!`.

**Comment by 1995eaton** [comment]
Strange, mind sharing your config?

**Comment by SirVer** [comment]
https://gist.github.com/SirVer/b791f88fc93465ab7927

**Comment by SirVer** [comment]
And my keymap is this one http://www.neo-layout.org/

**Comment by 1995eaton** [comment]
I think I see the problem. In cVim, there are two types of mappings: ones configured via the config file and ones configured in the `Keyboard shortcuts` section located at the bottom right of `chrome://extensions`. The second type of mappings are allowed to work on URLs that the first type of mappings won't work on because of limitations in the Chrome extensions API. Remove the default mappings there and cVim should work as expected. I've went ahead and removed the suggested keys in the [manifest.json](https://github.com/1995eaton/chromium-vim/blob/master/manifest.json) file so `<A-k>` and `<A-j>` aren't mapped by default.

**Comment by SirVer** [comment]
That's it, now it works! Thanks for your help.
