### ISSUE TITLE
Error: Mappings is not defined

### ISSUE THREAD

**Issue by boxofrox** [1995eaton/chromium-vim#254]
While visiting a github repo (https://github.com/plataformatec/simple_form), cVim flaked out and stopped responding to keystrokes.  Chrome still processed keys fine `Ctrl`+`R` to reload, etc.  Tried reloading the site multiple times to no avail, then checked the console and found this error message.

    Error in event handler for (unknown): ReferenceError: Mappings is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:151:7

Reloaded the page with dev-tools open to verify the error occurs when the page loads, and upon this reload, cVim navigation started working.

Overall, I'm finding cVim quits responding to keystrokes sporadically.  I imagine I'm pressing something I shouldn't be, but I can never figure out what it was when cVim zones out.  Pressing `Esc` repeatedly doesn't return to a workable state (i.e. navigation mode).  I can reproduce this most often by loading a site in tab, press `o` to open page, press `Esc` to cancel, and cVim stops responding until a `Ctrl`+`R` reloads cVim.  Not sure if this is related to the mapping error.  If not I can move this portion into its own issue upon request.

Running Chromium 40.0.2214.111-1 on Arch Linux.

**Comment by 1995eaton** [comment]
Definitely not something you're doing wrong. I've experience this a couple of times (seemingly at random) and am trying to figure out what's going wrong. I'll keep this issue open until I can get to the bottom of this. Thanks for the submission + error description!

**Comment by boxofrox** [comment]
Good to know.  I'll keep searching for a more reliable list of steps to reproduce the issue.  Shortly after the OP, using `o` followed by `Esc` began to work as expected (i.e. returned to navigation mode).

**Comment by kevincolyar** [comment]
Getting the same error messages working on a clojurescript + om app locally at http://localhost:3001.  Clojurescript does use Google's closure engine... maybe it's conflicting with cVim?

**Comment by boxofrox** [comment]
Is Google closure built into Chrome or a separate js download?  If the latter, I'll check the list of sources when I find another site where cVim stops responding.

**Comment by 1995eaton** [comment]
I don't think ClojureScript is the problem here. I've had this problem happen on several different domains and the problem always resolves itself after a couple of page refreshes. The issue seemed to present itself shortly after I moved the command bar to an `<iframe>`, so that might have something to do with it. Anyways, I haven't experience the problem in about a week, so I'm just waiting for it to happen again so I can start debugging. You guys might be able to rule out (or confirm) issues with cVim's `<iframe>` by opening up the JavaScript console after the problem occurs and switching to the command bar frame (`cmdline_frame.html`) and checking for any irregularities (like `Mappings`, etc not being defined).

**Comment by ArtBIT** [comment]
Every time this occurs, I can see one of the following errors in the console:

 - Error in event handler for runtime.onMessage: ReferenceError: Find is not defined at chrome-extension://.../content_scripts/messenger.js:180:7
 - VM38 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Mappings is not defined at chrome-extension://.../content_scripts/messenger.js:153:7
 - VM38 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Command is not defined at chrome-extension://.../content_scripts/messenger.js:63:9
 - VM38 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Mappings is not defined at chrome-extension://.../content_scripts/messenger.js:59:7
 - extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: ReferenceError: Find is not defined  at chrome-extension://.../content_scripts/messenger.js:180:7
 - extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Search is not defined at chrome-extension://.../content_scripts/messenger.js:94:7
 - extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: ReferenceError: Find is not defined at chrome-extension://.../content_scripts/messenger.js:180:7

**Comment by s-kostyaev** [comment]
Chromium 41.0.2272.89 (64-bit). Errors from console:

extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Mappings is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:153:7
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Marks is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:121:7
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Command is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:63:9
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Mappings is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:59:7
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Marks is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:91:7
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): ReferenceError: Search is not defined
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/content_scripts/messenger.js:94:7

**Comment by fightingdreamer** [comment]
I'm also experiencing this issue (usually when starting browser), similar errors as above.

When starting browser:
- cvim on active tab always works (probably because chrome load this tab first).
- cvim on other tabs, with the same url rarely works (~20 open tabs ~5 pinned, however this also happens with only two open tabs, but it's very rare).
- cvim on other tabs, with other urls works at random (~20 open tabs ~5 pinned).

Additional thoughts:
- disabling all other extensions, does not change anything.
- looks like more open tabs, more chance to hit this issue.
- the similar error appears in dev console, when cvim options page loads as empty (rare, but still happens, probably related to #138).
- amount and order of errors can vary between tabs.
- sometimes cvim button state will be gray when this issue happens, but is not 100% accurate.

For me it looks like some kind of race condition.

cVim (1.2.73) on Google Chrome 41.0.2272.118
Logs: http://pastebin.com/bKQvxh17
Iframe: http://pastebin.com/DviRjMyM

**Comment by 1995eaton** [comment]
It looks like I had the `messenger.js` script set to load before other scripts like `mappings.js`. After the messenger script gets an initial reply from the background thread, it tries to access several objects that may not be defined yet. I changed the HTML so that `messenger.js` loads last. So far, the change seems to be working for me. Let me know if it works for you guys too and I'll close the issue.

**Comment by boxofrox** [comment]
Testing in progress.  Will report back in a day or two.

**Comment by boxofrox** [comment]
I've not seen any `Mappings is not defined` errors, since I upgrade cVim, yesterday.  Will report back tomorrow whether the error appears.

**Comment by boxofrox** [comment]
@1995eaton, cVim has worked flawlessly the last couple days.  :+1: to close.  thank you.

**Comment by fightingdreamer** [comment]
Works for me too, also "cvim options page loads as empty" never appeared from 556a883059d4cc9a39fb2da8eed66fbcfd2a6368 onward.

**Comment by ArtBIT** [comment]
I confirm the fix as well.

**Comment by s-kostyaev** [comment]
Works for me too.
