### ISSUE TITLE
Display source code in new tab?

### ISSUE THREAD

**Issue by tkossak** [1995eaton/chromium-vim#287]
`gs` displays source in current tab, can i open it somehow in new tab?

**Comment by Fruglemonkey** [comment]
You can do this functionality yourself with a custom mapping: 

map gs :tabnew= view-source:@%<CR>

**Comment by 1995eaton** [comment]
579da1e should fix this issue (changed `gs` mapping to `:viewsource!<CR>` instead of `:viewsource&<CR>`). In addition to what @Fruglemonkey suggested, you can change the way commands open tabs (whether they're active, inactive, pinned) by referencing the tabs section of the README: https://github.com/1995eaton/chromium-vim/blob/master/README.md#tabs

**Comment by Fruglemonkey** [comment]
Yeah, before this commit I tried out goToSource! and goToSource&, to no avail.
