### ISSUE TITLE
Searching causes javascript click handlers to break

### ISSUE THREAD

**Issue by brianpeiris** [1995eaton/chromium-vim#389]
Steps to reproduce:

1. Visit this simple test page: http://output.jsbin.com/heyedo
2. Click on the button labeled "bar" and see that its background color changes when you click on it.
3. Open the search bar with `/`
4. Search for "tes" or "test" 
  - The search string must be at least 3 characters and must exist on the page in order to reproduce this bug.
5. Now try clicking on the button again and see that the background color no longer changes

My preliminary debugging shows that you replace the `innerHTML` of elements at some point during the search. This causes DOM elements to be replaced by new instances (though with the same content), so Javascript handlers are lost with the removal of the old instances.

**Comment by 1995eaton** [comment]
Should be fixed now. The only reason I was replacing `innerHTML` in the first place was because it performed about twice as fast as `replaceChild`. Now that I know that using `innerHTML` causes issues, I guess that forces me to use the `replaceChild` method unless someone can think of a faster way to do this that doesn't break webpages.
