### ISSUE TITLE
Pasting a keyword using p/P ignores defaultengine

### ISSUE THREAD

**Issue by juodumas** [1995eaton/chromium-vim#415]
I am using `let defaultengine = "duckduckgo"`. But when I have e.g. `cVim` in the clipboard and press 'P', cVim opens a new tab with a Google search instead of a DuckDuckGo search. `:tabopen cVim` is working as expected.

**Comment by s-kostyaev** [comment]
You also need to setup duckduckgo as default search engine in chrome settings.

**Comment by juodumas** [comment]
But I have. When I search for 'cVim' using the browser's address bar,
results come from duckduckgo.

**Comment by s-kostyaev** [comment]
```
let searchengine dg = "https://duckduckgo.com/?q="
let defaultengine = "dg"
``` 
in `cvimrc` works fine for me.

**Comment by juodumas** [comment]
Still doesn't work here. Tested on a clean profile with both, cVim 1.2.81 and git master. `:open anything`, `tabopen anything`, search in Chromium's location bar all go through DuckDuckGo, but `:call openPaste` (with 'anything' in the clipboard) opens Google Search. Here is a 20 second screen capture: http://3.sendvid.com/d7idsi1o.mp4

**Comment by kosl90** [comment]
I gets the same problem with cVim 1.2.84 and google chrome 51.0.2704.79 m (64-bit) on Windows.

In cvimrc:
```
let searchengine baidu = "https://www.baidu.com/s?wd="

let defaultengine = "baidu"
```

As my trace in the newest code, [tabnew](https://github.com/1995eaton/chromium-vim/blob/master/content_scripts/command.js#L739) series commands are mapped to [openLink](https://github.com/1995eaton/chromium-vim/blob/master/background_scripts/actions.js#L31) action, the passed value is encoded by [Complete.convertToLink](https://github.com/1995eaton/chromium-vim/blob/master/content_scripts/complete.js#L47). Because Complete.convertToLink will handle 'defaultengine', 'defaultengine' works fine.
```javascript
  if (/^(tabnew|tabedit|tabe|to|tabopen|tabhistory)$/
      .test(value.replace(/ .*/, ''))) {
    tab.tabbed = true;
    RUNTIME('openLink', {
      tab: tab,
      url: Complete.convertToLink(value, tab.isURL, tab.isLink),
      repeats: repeats,
      noconvert: true
    });
    return;
  }
```
```javascript
convertToLink: function(input, isURL, isLink) {
   // ignore some code
    if (!this.hasEngine(input[0])) {
      if (!isLink && (isURL || input.join(' ').validURL())) {
        input = input.join(' ');
        return (!/^[a-zA-Z\-]+:/.test(input) ? 'http://' : '') +
          input;
      }
      var defaultEngine = this.getEngine(settings.defaultengine);
      return (defaultEngine ? defaultEngine.requestUrl :
                              this.getEngine('google').requestUrl) +
        encodeURIComponent(input.join(' '));
    }
   // ignore some code
}
```
However, [String.prototype.convertLink](https://github.com/1995eaton/chromium-vim/blob/master/content_scripts/utils.js#L142) in which google search engine is hard coded is used in '[openPaste](https://github.com/1995eaton/chromium-vim/blob/master/background_scripts/actions.js#L4107)' and '[openPasteTab](https://github.com/1995eaton/chromium-vim/blob/master/background_scripts/actions.js#L387)'.

  ```javascript
_.openPaste = function() {
    var paste = Clipboard.paste();
    if (!paste) {
      return;
    }
    paste = paste.split('\n')[0];
    chrome.tabs.update({
      url: paste.convertLink()
    });
  };
```

```javascript
definePrototype(String, 'convertLink', function() {
  if (this.validURL()) {
    return (!/^[a-zA-Z\-]+:/.test(this) ? 'http://' : '') + this;
  }
  return 'https://www.google.com/search?q=' + encodeURIComponent(this);
});
```

**Comment by kosl90** [comment]
@1995eaton great job again!!!
