### ISSUE TITLE
f opens link in new tab

### ISSUE THREAD

**Issue by justin-murphy** [1995eaton/chromium-vim#557]
f should open link in current tab not a new tab.

**Comment by Thau** [comment]
@justin-murphy It does if you write the link code in lowercase. If you write it in uppercase, then it opens it in a new tab.

**Comment by cedric-sun** [comment]
@justin-murphy `f` behave like a simple left-click on the link. So if `target="_blank"` is set in the HTML anchor element, `f` opens & focus on a new tab just like a left-click does.

I guess this is because Chrome doesn't provide an API like `Open link in current tab even overwriting the current content` (At lease, I can use `Ctrl + left_click` to force Chrome to open link in a new tab, but I don't see any way to do its inverse.)

**Comment by 1995eaton** [comment]
@cedric-sun is correct. The `f` key "tries" to act as if you click the link with the mouse.
