### ISSUE TITLE
Doesn't open a new tab when open :bookmark 

### ISSUE THREAD

**Issue by Armog** [1995eaton/chromium-vim#685]
When we use "b" to open bookmarks, bookmark opens in current tab, but not in a new tab. It is not useful if you want to open a new bookmark from the current worked tab.
Thanks for cVim!

**Comment by andremeireles** [comment]
`Ctrl + Enter`

**Comment by D12EA177E12** [comment]
@andremeireles `Ctrl + Enter` doesn't work for me here.

**Comment by andremeireles** [comment]
So it could be a built-in feature from my default web browser `vivaldi`.

**Comment by Armog** [comment]
Ctrl + Enter works fine in Chrome and opens bookmark in new tab as well.
Maybe it will be handy if bookmarks open without additional shortcut.
For example, in case with 't' (open tab) URL opens in new tab by default.

**Comment by andremeireles** [comment]
I read the doc and saw that is possible remap the b shortcut permanetly on cvim's options, like you want whit this snnipet:

`map b :bookmarks!<space>` - will works like `t` but for bookmarks.

or if someone want open a new tab only once, just press `b`, add a exclamation mark after `:bookmarks`, put a space and type your bookmark text.

I think it doesn't come by default this way because it's a specific case. Not all people want a bookmark to open in a new tab.

**Comment by conceptrat** [comment]
When you use the bookmarks shortcut "b" it essentially triggers the command mode ":bookmarks " and goes straight to searching bookmarks.  Because the "boomarks" command opens links you can apply the properties mentioned in the "Tabs" section of the cVim Help here [https://github.com/1995eaton/chromium-vim#tabs](https://github.com/1995eaton/chromium-vim#tabs).

So press "b". Then search/select the bookmark you want to open, add the property(s) at the end and press [ENTER] or you can backspace one character type in the property(s) first, then a [SPACE], then select the bookmark and press [ENTER].  To open the bookmark in a newtab use "!", a new window "$" and a new incognito window "|".  And if you don't want it to be focused (load in background) then also add "&".

For example after pressing "b" and doing everything but pressing [ENTER] you might see this in the command window:

:bookmarks https://slashdot.org/$&

Which would open the bookmark "https://slashdot.org/" in a new window in the background (not focussed).
