### ISSUE TITLE
createHint not working with the latest version of Chrome

### ISSUE THREAD

**Issue by SudoHaugen** [1995eaton/chromium-vim#725]
Hello,

cVim 'createHint' function stopped working after I updated chrome to the newest version available (80.0.3987.100 32bit). I tested this on several computers which had a previous version of Chrome installed and createHint worked on all of them before I updated their Chrome (and it didn't work after the update). I have tested this with my own keymapping and with the standard keymapping

**Comment by srghma** [comment]
have this too

**Comment by dcchambers** [comment]
The latest version of chrome broke this because it deprecated `Element.createShadowRoot`. A fix has been submitted but has not been merged. For now you'll have to manually install the fix. [Instructions here.](https://github.com/1995eaton/chromium-vim/issues/716#issuecomment-583425260)

We're discussing the posibility of forking this into a maintained project as right now this project appears to no longer be maintained. See discussion here: #723

This is a dup of: #716 
For a fix, see PR #719 or #724

**Comment by robin521111** [comment]
![image](https://user-images.githubusercontent.com/1659299/74848276-7c006800-5372-11ea-9e7b-8ab91d03d978.png)
i solved this issue only with one line of code, but unluckily, since this repository was not updates anymore, so i can not push my code, i will later try folk it and update the latest source code. but anyway it is works fine in my chrome now.

**Comment by SudoHaugen** [comment]
> ![image](https://user-images.githubusercontent.com/1659299/74848276-7c006800-5372-11ea-9e7b-8ab91d03d978.png)
> i solved this issue only with one line of code, but unluckily, since this repository was not updates anymore, so i can not push my code, i will later try folk it and update the latest source code. but anyway it is works fine in my chrome now.

Yes I solved this problem in a similar way as you, but unfortunately you have to run the app in developer mode in Chrome which is not recommended due to security issues

**Comment by pak11273** [comment]
Follow this reddit for a working solution: https://www.reddit.com/r/chromeos/comments/exo87u/vimiumcvim_extensions_f_key_doesnt_work_on_my/
